services:
  nodejs-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/allfunds
    depends_on:
      - mongodb
    develop:
      watch:
        - action: sync
          path: .
          target: /app

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
